- database/migrations/2014_10_12_000000_create_users_table.php
> 重複していたregisterファイルの削除とusersテーブル作成

- app/Http/Controllers/Auth/RegisterController.php
- app/Models/User.php
- database/migrations/2014_10_12_000000_create_users_table.php
- resources/views/auth/register.blade.php
> city追加と新規登録でtelを入力可能にした

- app/Http/Controllers/UserController.php
- resources/views/tops/create_profile.blade.php
- routes/web.php
私のパソコンにはまだデータベースや最新のコードが反映されていないため、storeのsaveとredirectはコメントアウトしてます。 storeのURLは一旦で適当につけてます。
> 初回プロフィール作成view

- app/Http/Controllers/MypageController.php
- resources/views/mypages/mypage.blade.php
- routes/web.php
imgはまだです。
ブックマークした投稿の一覧表示などもまだです。
> マイページにてプロフィール表示

- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/QuestionController.php
- app/Http/Controllers/TopController.php
- app/Http/Controllers/UserController.php
- app/Models/Question.php
- database/migrations/2024_09_08_091635_create_questions_table.php
- resources/views/tops/question.blade.php
- routes/web.php
新たに、migrationファイルで、questionsテーブルを作成しました。
> アンケートページ作成

- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/MypageController.php
- app/Http/Controllers/SubscriptionController.php
- app/Http/Controllers/UserController.php
- app/Models/Status.php
- database/migrations/2024_09_08_083019_create_statuses_table.php
- resources/views/mypages/subscription1.blade.php
- resources/views/tops/create_profile.blade.php
> 新規登録と同時にステータスレコード作成

- app/Http/Controllers/BookmarkController.php
- app/Http/Controllers/LikeController.php
- app/Http/Controllers/PostController.php
- app/Models/Bookmark.php
- app/Models/Like.php
- resources/views/posts/index.blade.php
- routes/web.php
ブックマーク機能といいね機能を追加しました。
ブックマークされた数といいね数が表示されるようになりました。
> ブックマークといいね

- app/Http/Controllers/SubscriptionController.php
- resources/views/layouts/app_original.blade.php
> ハンバーガーメニュー作成

- app/Http/Controllers/PostController.php
- resources/views/posts/create_check.blade.php
- resources/views/posts/create_post.blade.php
- resources/views/tops/question.blade.php
- routes/web.php
新規投稿作成画面で入力したデータを確認画面に飛ばして表示されるようにしています。
確認画面で、「投稿」ボタンを押すと、投稿一覧画面に投稿が表示されるとともに、データベースにデータが保存されるようになっています。
また、確認画面で「戻る」ボタンを押すと、新規投稿作成画面で入力したデータがそのまま残っている状態で表示されるようにしています。
> 新規投稿作成・確認画面

- app/Http/Controllers/MypageController.php
- app/Models/User.php
- resources/views/mypages/mypage.blade.php
> マイページ機能ほぼ完了

- app/Http/Controllers/BmCoinController.php
- app/Models/Coin.php
- app/Models/User.php
- database/migrations/2024_09_09_105822_create_coins_table.php
- resources/views/mypages/bmcoin1.blade.php
- resources/views/mypages/bmcoin2.blade.php
- resources/views/mypages/bmcoin3.blade.php
- resources/views/mypages/mypage.blade.php
- routes/web.php
追加でcoinモデルとマイグレーションを作ってます。（migrateは俺もまだしてない）
決済関連はまだ。
データベース上での計算もまだ。
> 選択した商品の情報を受け取りながら次の画面に遷移

- app/Http/Controllers/BmCoinController.php
- app/Http/Controllers/ExchangeController.php
- app/Models/Amazon.php
- database/migrations/2024_09_12_120250_create_amazons_table.php
- resources/views/layouts/app_original.blade.php
- resources/views/mypages/exchange.blade.php
- routes/web.php
migrationファイルを作っています。migrateしてね。
> ブックマークをAmazonギフト券に交換（作成途中）

- app/Console/Kernel.php
- app/Http/Controllers/MypageController.php
- app/Models/Post.php
- database/migrations/2024_09_14_040214_add_deleted_at_to_posts_table.php
- resources/views/welcome.blade.php
> ソフトデリート(できたりできなかったり)

- app/Console/Kernel.php
- app/Http/Controllers/PostController.php
- app/Models/Post.php
- database/migrations/2024_09_16_204546_add_deletion_date_to_posts_table.php
- resources/views/posts/index.blade.php
- routes/web.php
100コイン払うと1日延長
投稿者のみ延長可能
アラート表示
> ソフトデリート期間延長

- app/Http/Controllers/AdminController.php
- app/Models/Report.php
- resources/views/admin/reports.blade.php
> 悪質報告受け取り完了

- app/Console/Kernel.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/MypageController.php
- resources/views/mypages/mypage.blade.php
> Trial期間を設定。1日間は有料と同じ扱い

- app/Http/Controllers/BookmarkController.php
- app/Http/Controllers/PostController.php
- composer.lock
- resources/views/posts/index.blade.php
> ブックマークするときに忠告文が出ます

- app/Http/Controllers/ContactController.php
- app/Models/Contact.php
- database/migrations/2024_09_17_203705_create_contacts_table.php
- resources/views/contact/complete.blade.php
- resources/views/contact/confirm.blade.php
- resources/views/contact/form.blade.php
- resources/views/layouts/app_original.blade.php
- routes/web.php
お問い合わせ用のテーブルを新規作成したのでmigrateお願いします。
ざっくりですが、ユーザーからのお問い合わせが集められるようになってるはずです。
ヘッダーメニューにもリンク追加しました。
管理者側は未対応です。
> お問い合わせフォーム作成しました

- public/css/posts.index.css
- resources/views/posts/index.blade.php
> 投稿一覧でコピペはできなくしました

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/ContactController.php
- app/Models/Contact.php
- app/Models/User.php
- database/migrations/2024_09_17_203705_create_contacts_table.php
- resources/views/admin/inbox.blade.php
- resources/views/contact/confirm.blade.php
- resources/views/contact/form.blade.php
- routes/web.php
> 管理者画面お問い合わせ

- app/Http/Controllers/BookmarkController.php
- public/js/posts.index.js
- resources/views/posts/index.blade.php
ブックマークを非同期でできるようにしました。
ブックマークを押してリロードをするとブックマーク数の変更が反映されます
> ブックマークの非同期

- app/Http/Controllers/LikeController.php
- public/css/posts.index.css
- public/js/posts.index.js
- resources/views/posts/index.blade.php
いいねのハートの色の変化がどれだけ強制しても非同期化できません。リロードしたらハートの色は変わります。このアプリでいいねはそこまで重要ではないと思うのでここの課題は一旦パスさせていただきたい。
> ハートマークの非同期化

- app/Http/Controllers/UserController.php
- resources/views/tops/create_profile.blade.php
プロフィールを更新するときに今までは毎回画像をアップロードしなければなりませんでしたが、それをしなくても引き続き表示されるようになりました。
> プロフィール作成・編集

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/ReportController.php
- app/Models/User.php
- resources/views/admin/admin_layout.blade.php
- resources/views/admin/exchange.blade.php
- resources/views/admin/exchange_partial.blade.php
- resources/views/admin/inbox.blade.php
- resources/views/admin/inbox_partial.blade.php
- resources/views/admin/menu.blade.php
- resources/views/admin/reports.blade.php
- resources/views/admin/reports_partial.blade.php
- resources/views/ads/create.blade.php
- resources/views/contact/complete.blade.php
- resources/views/reports/create.blade.php
- routes/web.php
管理者画面検索機能つきました。
inboxはもう少し調整予定です。
> たぶん非同期の検索機能追加

- app/Http/Controllers/AdController.php
- app/Http/Controllers/AdminController.php
- resources/views/admin/inbox.blade.php
- resources/views/admin/reports.blade.php
- resources/views/ads/create.blade.php
- resources/views/contact/form.blade.php
- resources/views/reports/create.blade.php
微修正（コントローラー修正バーション）
広告追加：ラベルの色チェンジ
管理者お問い合わせ　ページネーション削除
お問い合わせバリデーション対策
>  微修正（コントローラー修正バーション）
